service: hello-sample

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  deploymentBucket: !ImportValue code-pipeline-common:bucket

package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
