service: code-pipeline-common

provider:
  name: aws
  region: eu-west-1

resources:
  Description: code pipeline common account resources

  Resources:

    CodePipelineS3Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete

    CodePipelineIamRole:
      Type: AWS::IAM::Role
      Properties:
        Path: "/"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: AssumeRole
              Effect: Allow
              Principal:
                Service:
                  - codepipeline.amazonaws.com
                  - codebuild.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AdminPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Sid: admin
                  Effect: Allow
                  Action: "*"
                  Resource: "*"

  Outputs:
    CodePipelineBucket:
      Value: !Ref CodePipelineS3Bucket
      Export:
        Name: ${self:service}:bucket
    CodePipelineRole:
      Value: !GetAtt CodePipelineIamRole.Arn
      Export:
        Name: ${self:service}:role
